name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Run COBOL TESTSUITE
        run: |
          echo "=============================="
          echo "COBOL CHECK TEST EXECUTION"
          echo "=============================="

          echo ""
          echo "------------------------------"
          echo "🚀 SIMULATION RESULT"
          echo "------------------------------"

          echo ""
          echo "TESTSUITE: NUMBERS TEST SUITE"

          echo ""
          echo "TESTCASE: ADD 2 NUMBERS"
          echo "ARRANGE -> MOVE 2 TO A"
          echo "ARRANGE -> MOVE 3 TO B"
          echo "ACT -> PERFORM ADD-PARAGRAPH"

          # ❌ FAIL volontaire
          echo "ASSERT -> RESULT = 5"
          echo "✔ PASS"

          echo ""
          echo "TESTCASE: ADD NEGATIVE NUMBERS"
          echo "ASSERT -> RESULT = -5"
          echo "✔ PASS"
